apiVersion: v1
data:
  aws-access-key-id: ${AWS_ACCESS_KEY_ID_BASE64}
  aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY_BASE64}
kind: Secret
metadata:
  namespace: support
  name: support-aws-keys
type: Opaque
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: support
  name: support-bundle
spec:
  backoffLimit: 1
  template:
    metadata:
      namespace: support
      name: support-bundle
    spec:
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: ${HOSTNAME}
      containers:
      - args:
        - support-bundle.sh
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: support-aws-keys
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: support-aws-keys
              key: aws-secret-access-key
        securityContext:
          privileged: true
        image: platform9/support:latest
        name: support-bundle
        volumeMounts:
          - mountPath: /tmp/root
            name: root
      hostNetwork: true
      hostPID: true
      volumes:
        - hostPath:
            path: /
            type: Directory
          name: root
